### PR TITLE
fix: require @babel/preset-env instead of babel-preset-env

### PR DESCRIPTION
**Pull request by buschtoens**
We're listing `@babel/preset-env` as a dependency and so should be using it. 😄 

This was the reason for transpilation failing on me for IE11, because some old incompatible transforms are used by `babel-preset-env`.

AFAICT I can now fully build our TypeScript app with _just_ ember-cli-babel. 😍 🎉 

Simple demo repo here: https://github.com/buschtoens/ember-typescript-babel-7

Thank you guys *so much*. ❤️ 

Closes #236, because it branched off of it.

### CODE REVIEW

**Comment by buschtoens** [comment]
One more thing: I added `@babel/core@^7.0.0-beta.56` as a dev dep. But it should probably be a real dependency, right? Because right now the host app needs to install `@babel/core` for us. Is this intentional?

**Comment by rwjblue** [comment]
> Because right now the host app needs to install @babel/core for us.

No, `broccoli-babel-transpiler` has a direct dependency on `@babel/core`.

**Comment by rwjblue** [comment]
Can you rebase (@dfreeman got CI passing in #239)?

**Comment by buschtoens** [comment]
> No, broccoli-babel-transpiler has a direct dependency on @babel/core.

True! Also noticed that. The problem for me was, that some of my transforms had a peer dep on `^beta.56`, but `broccoli-babel-transpiler` has `42` or something like that.

So I guess this PR is outdated now. I'll rebase #236 instead.

**Pull request closed without merging**
