### PR TITLE
deprecationMessage tweaks

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by goldenice** [comment]
Err, this breaks it again. The error is `Cannot read property 'writeDeprecateLine' of undefined`, which implies that `this.ui` is undefined, not the function itself. This still causes the same error because you removed my check of `this.ui` seperately again.

**Comment by kellyselden** [comment]
My apologies. I tweaked your code to match some of the existing code in the file as far as ui checking. I will fix.

**Comment by goldenice** [comment]
No problem :+1: Happens to the best of us :wink:

**Comment by kellyselden** [comment]
How is 5.2.7?

**Comment by goldenice** [comment]
Works like a charm :+1: Thanks for your quick follow-up, I really appreciate it :smile:

**Pull request merged**
