### PR TITLE
add a no-op optimization

### LINKED ISSUE #201: detect when no plugins are added and no-op
Discovered as a new optimization from https://github.com/ember-cli/ember-cli/pull/7501.

cc @rwjblue

### PR DESCRIPTION
**Pull request by kellyselden**
Closes #201

### CODE REVIEW

**Comment by stefanpenner** [comment]
@kellyselden I like this, but can you add a quick unit test for that hook, ensuring that this works as expected (and continues to into the future)

**Comment by kellyselden** [comment]
@stefanpenner added a test

**Comment by kellyselden** [comment]
@rwjblue That's essentially what my test is. What would you like changed?

**Comment by stefanpenner** [comment]
released as v6.12.0 🎉

**Pull request merged**
