### PR TITLE
WIP: Avoid eagerly requiring plugins/presets.

### PR DESCRIPTION
**Pull request by rwjblue**
This is a quick spike to enable parallel transpilation with our default configuration.

/cc @stefanpenner @mikrostew

### CODE REVIEW

**Comment by rwjblue** [comment]
The primary issue with _not_ `require`ing these plugins directly is that they will not be resolved relative to ember-cli-babel itself (instead they will be resolved from the top-level node_modules dir as if they were direct project deps). This would break having multiple independent versions of ember-cli-babel.

**Comment by rwjblue** [comment]
I believe that we can fix that by using `resolve.sync` to resolve the full paths relative to ember-cli-babel, and that `babel` itself allows you to specify a fully qualified path to require as the plugin name.

**Comment by stefanpenner** [comment]
@rwjblue i think we can use https://github.com/babel/broccoli-babel-transpiler#requirefile-required + `require.resolve`, right? cc @mikrostew

**Comment by stefanpenner** [comment]
Also, complementary PR: https://github.com/babel/broccoli-babel-transpiler/pull/137

**Comment by mikrostew** [comment]
To avoid breaking multiple version of ember-cli-babel, it looks to me that we can use `require.resolve` to get the full path as seen from ember-cli-babel, and pass that full path to babel: https://babeljs.io/docs/plugins/#pluginpreset-paths

**Pull request closed without merging**
