### PR TITLE
[CHORE BREAKING] bump node support to 10, 12+

### PR DESCRIPTION
**Pull request by runspired**

### CODE REVIEW

**Comment by Turbo87** [comment]
this would break lockstep with Babel itself... I'm wondering if there is a real need to do this 🤔

**Comment by runspired** [comment]
Are we in lockstep more than by accident?

**Comment by Turbo87** [comment]
afaik yes

**Comment by rwjblue** [comment]
Hmm, I wouldn't assume we are trying to match babel majors here :thinking:

The thing that _actually_ brings babel is broccoli-babel-transpiler, and it's only 6.x anyways...

**Comment by bertdeblock** [comment]
Closing in favor of #454 if that's okay.

**Pull request closed without merging**
