### PR TITLE
Toggle code highlighting for broccoli-middleware >= 2.1.0

### PR DESCRIPTION
**Pull request by astronomersiva**
This is needed to unlock https://github.com/ember-cli/broccoli-middleware/pull/51

### CODE REVIEW

**Comment by astronomersiva** [comment]
Tried writing tests for this along the lines of

```js
it('returns true when broccoli-middleware version is greater than or equal to 2.1.0', function() {
  this.addon.parent = {
    dependencies() { return { 'broccoli-middleware': '2.1.2' }; }
  };

  expect(this.addon._shouldHighlightCode()).to.be.true;
});
```
but `_shouldHighlightCode()` always returns false as the installed version of `broccoli-middleware` in `node_modules` is 1.2.1.

**Comment by astronomersiva** [comment]
@stefanpenner please take a look.

**Comment by astronomersiva** [comment]
@stefanpenner please take a look at this as well

**Comment by astronomersiva** [comment]
@stefanpenner a friendly ping :)

**Comment by astronomersiva** [comment]
@stefanpenner @rwjblue can you please take a look at this if you are free?

**Comment by stefanpenner** [comment]
@astronomersiva sorry for letting this sit, looks great!

**Pull request merged**
