### PR TITLE
Expose addon powerz

### PR DESCRIPTION
**Pull request by stefanpenner**
paired with @rwjblue (with our powerz combined..)

e654548d15b94ef877bc93aa1a28b1aeac9ddecbb7c84c3f0b3d100a2c33c921

### CODE REVIEW

**Comment by stefanpenner** [comment]
note: this should be released as the next beta, so `6.0.0-beta.10`

**Comment by stefanpenner** [comment]
Don't merge yet, there are some issues to resolve.

**Comment by rwjblue** [comment]
@stefanpenner - you published as `--tag latest` (the default), it should have been `--tag beta`

**Comment by stefanpenner** [comment]
@rwjblue oops

**Pull request merged**
