### PR TITLE
Only blacklist jQuery module when parent depends on @ember/jquery itself

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes https://github.com/babel/ember-cli-babel/issues/263

### CODE REVIEW

**Comment by rwjblue** [comment]
@simonihmig - Would you mind sanity checking this one?

**Comment by rwjblue** [comment]
> But this would not explain the error reported in emberjs/ember-test-helpers#545, as at least one addon would have @ember/jquery as a dependency, so the jQuery module shim would be available, right?

Yes, I'm waiting for a concrete reproduction, but I was able to reproduce the failure by having done `npm install @ember/jquery && git checkout package.json` (basically installing the addon into node_modules, but not listing it in package.json).

> If we apply the changes here, this could lead to a situation, where a couple of addons might effectively rely on jQuery, but only those that had been updated to list @ember/jquery as a dependency would import jQuery form the shim, and the others would still use ember.$, thus triggering a deprecation, right? Which would work, and maybe even be useful to nudge those addons to list @ember/jquery as a dependency.

Yes, exactly.

> But on the other hand, if there are unmaintained addons, a user would not be able to quash the deprecation or even update to Ember 4 by just installing @ember/jquery in the app itself, which would be possible right now!

I agree, this seems non-ideal. 🤔 I think we should address this by also checking project deps, what do you think?

**Comment by rwjblue** [comment]
@simonihmig I just pushed another commit with that change, what do you think?

**Comment by simonihmig** [comment]
> I think we should address this by also checking project deps, what do you think?

Yes, I think that makes sense! 👍

**Pull request merged**
