### PR TITLE
Change name of variable to be more accurate

### PR DESCRIPTION
**Pull request by patocallaghan**
Just a tiny bit of cleanup from #387. This suggested variable rename was missed in the original PR.

### CODE REVIEW

**Comment by pzuraq** [comment]
oh huh, could have sworn I changed this 🤔  my bad, thanks for the update!

**Comment by patocallaghan** [comment]
@pzuraq you did `PRE_EMBER_MODULE_IMPORTS_VERSION`, this is `POST_EMBER_MODULE_IMPORTS_VERSION`

**Comment by pzuraq** [comment]
Ahhh, that was it 😄

**Review by rwjblue — APPROVED** [review]
Thank you!

**Pull request merged**
