### PR TITLE
Resolves #25 - handle non-nested addon options

### LINKED ISSUE #25: not picking up custom 'babel' options in 0.2.0 ember-cli
I am trying to prevent the default `compact` behavior of babel

I set 
```
new EmberApp({
    babel: {
        compact: false
    },
```
that option is never seen in the invocation of babel

I'm logging this.parent.options in setupPreprocessorRegistry and it's undefined.

logging this while I look for correct solution

### PR DESCRIPTION
**Pull request by jschilli**

### CODE REVIEW

**Comment by rwjblue** [comment]
This error is due to the rimraf/glob issue.  Submitting another pull request to take care of updating to ember-cli 0.2.0 which should fix this.  Then you can force push to re-run...

**Comment by rwjblue** [comment]
Should be good once #28 lands.

**Comment by jschilli** [comment]
thx - seems obvious now to me

**Comment by stefanpenner** [comment]
re-built. all is well.

**Pull request merged**
